stages:
  - compile
  - test

build:
  stage: compile
  image: golang:latest
  script:
    - go get -d -v ./cmd
    - go build -o bin/lumerin -v ./cmd

test:
  stage: test
  image: golang:latest
  script: 
    - go test ./cmd/accountingmanager/...
    - go test ./cmd/config/...
    - go test ./cmd/connectionscheduler/...
    - go test ./cmd/localvalidator/...
    - go test ./cmd/log/...
    - go test ./cmd/lumerinnetwork/...
    - go test ./cmd/msgbus/...
    - go test ./cmd/protocol/...
    - go test ./cmd/walletmanager/...
    - go test ./lumerinlib/...

