#!/bin/sh

go test ./cmd/accountingmanager/...
go test ./cmd/config/...
go test ./cmd/connectionscheduler/...
go test ./cmd/localvalidator/...
go test ./cmd/log/...
go test ./cmd/lumerinnetwork/...
go test ./cmd/msgbus/...
go test ./cmd/protocol/...
go test ./cmd/walletmanager/...
go test ./lumerinlib/...